let data =  {
    "BoardVersion": "0",
    "IsBetsAllowed": true,
    "IsBoardDisabled": false,
    "IsFinnished": false,
    "IsGameFinished": false,
    "IsGameStarted": true,
    "IsObserver": false,
    "JackpotAmount": "341.30922",
    "Last100SpinNumbers": 
        {
            0: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67875},
            1: {"Number": 23, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67871},
            2: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67868},
            3: {"Number": 31, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67865},
            4: {"Number": 24, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67862},
            5: {"Number": 5, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67859},
            6: {"Number": 36, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67856},
            7: {"Number": 12, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67852},
            8: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67848},
            9: {"Number": 36, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67845},
            10: {"Number": 30, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67841},
            11: {"Number": 33, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67837},
            12: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67834},
            13: {"Number": 6, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67831},
            14: {"Number": 31, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67828},
            15: {"Number": 19, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67826},
            16: {"Number": 11, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67823},
            17: {"Number": 22, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67820},
            18: {"Number": 23, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67817},
            19: {"Number": 27, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67814},
            20: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67811},
            21: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67807},
            22: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67804},
            23: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67801},
            24: {"Number": 10, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67798},
            25: {"Number": 31, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67795},
            26: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67792},
            27: {"Number": 28, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67789},
            28: {"Number": 2, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67786},
            29: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67783},
            30: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67779},
            31: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67776},
            32: {"Number": 17, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67773},
            33: {"Number": 24, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67770},
            34: {"Number": 30, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67767},
            35: {"Number": 28, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67763},
            36: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67760},
            37: {"Number": 33, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67757},
            38: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67753},
            39: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67750},
            40: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67747},
            41: {"Number": 25, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67744},
            42: {"Number": 5, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67741},
            43: {"Number": 23, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67738},
            44: {"Number": 12, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67734},
            45: {"Number": 0, "Color": "Green", "IsEven": null, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67731},
            46: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67727},
            47: {"Number": 26, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67724},
            48: {"Number": 21, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67720},
            49: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67717},
            50: {"Number": 26, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67714},
            51: {"Number": 22, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67711},
            52: {"Number": 32, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67708},
            53: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67705},
            54: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67701},
            55: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67698},
            56: {"Number": 14, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67695},
            57: {"Number": 2, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67692},
            58: {"Number": 27, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67689},
            59: {"Number": 29, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67685},
            60: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67682},
            61: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67679},
            62: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67675},
            63: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67672},
            64: {"Number": 22, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67669},
            65: {"Number": 5, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67665},
            66: {"Number": 34, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67662},
            67: {"Number": 9, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67658},
            68: {"Number": 33, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67655},
            69: {"Number": 16, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67652},
            70: {"Number": 22, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67648},
            71: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67645},
            72: {"Number": 8, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67642},
            73: {"Number": 19, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67639},
            74: {"Number": 31, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67634},
            75: {"Number": 2, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67630},
            76: {"Number": 6, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67626},
            77: {"Number": 24, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67622},
            78: {"Number": 6, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67619},
            79: {"Number": 1, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67615},
            80: {"Number": 23, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67612},
            81: {"Number": 18, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67609},
            82: {"Number": 36, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67606},
            83: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67603},
            84: {"Number": 13, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67599},
            85: {"Number": 24, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67596},
            86: {"Number": 4, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67593},
            87: {"Number": 14, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67590},
            88: {"Number": 33, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67587},
            89: {"Number": 27, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67584},
            90: {"Number": 7, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67581},
            91: {"Number": 26, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67579},
            92: {"Number": 35, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67576},
            93: {"Number": 13, "Color": "Black", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67573},
            94: {"Number": 23, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67571},
            95: {"Number": 3, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67569},
            96: {"Number": 27, "Color": "Red", "IsEven": false, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67567},
            97: {"Number": 12, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67565},
            98: {"Number": 10, "Color": "Black", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67563},
            99: {"Number": 18, "Color": "Red", "IsEven": true, "IsLucky": true, "IsClearSpin": false, "SpinNumber": 67561}
    },
    "LuckyNumber": null,
    "LuckyWinningNumber": null,
    "OnlinePlayers": 5,
    "Options": [],
    "PlayerInfo": {
        "AllowRebet": false,
        "AvailableAmount": 37911.11,
        "BetAmount": 0.01,
        "CompleteBet": false,
            "Currency":{
                "CurrencyCode": "GEL",
                "FractionDigit": 2,
            },
            "LatestSpins":{
                "0": {"SpinNumber": 63662, "BetAmount": 3.5, "WonAmount": 0, "SpinDate": "2019/11/25 13:04:45"},
                "1": {"SpinNumber": 63661, "BetAmount": 1.85, "WonAmount": 0, "SpinDate": "2019/11/25 13:03:54"},
                "2": {"SpinNumber": 63197, "BetAmount": 0.05, "WonAmount": 0, "SpinDate": "2019/11/22 11:48:20"},
                "3": {"SpinNumber": 57124, "BetAmount": 2.25, "WonAmount": 0, "SpinDate": "2019/11/18 11:37:00"},
                "4": {"SpinNumber": 63662, "BetAmount": 3.5, "WonAmount": 0, "SpinDate": "2019/11/25 13:04:45"},
                "5": {"SpinNumber": 63661, "BetAmount": 1.85, "WonAmount": 0, "SpinDate": "2019/11/25 13:03:54"},
                "6": {"SpinNumber": 63197, "BetAmount": 0.05, "WonAmount": 0, "SpinDate": "2019/11/22 11:48:20"},
                "7": {"SpinNumber": 57124, "BetAmount": 2.25, "WonAmount": 0, "SpinDate": "2019/11/18 11:37:00"},
                "8": {"SpinNumber": 63662, "BetAmount": 3.5, "WonAmount": 0, "SpinDate": "2019/11/25 13:04:45"},
                "9": {"SpinNumber": 63661, "BetAmount": 1.85, "WonAmount": 0, "SpinDate": "2019/11/25 13:03:54"},
                "10": {"SpinNumber": 63197, "BetAmount": 0.05, "WonAmount": 0, "SpinDate": "2019/11/22 11:48:20"},
                "11": {"SpinNumber": 57124, "BetAmount": 2.25, "WonAmount": 0, "SpinDate": "2019/11/18 11:37:00"},
                "12": {"SpinNumber": 63662, "BetAmount": 3.5, "WonAmount": 0, "SpinDate": "2019/11/25 13:04:45"},
                "13": {"SpinNumber": 63661, "BetAmount": 1.85, "WonAmount": 0, "SpinDate": "2019/11/25 13:03:54"},
                "14": {"SpinNumber": 63197, "BetAmount": 0.05, "WonAmount": 0, "SpinDate": "2019/11/22 11:48:20"},
                "15": {"SpinNumber": 57124, "BetAmount": 2.25, "WonAmount": 0, "SpinDate": "2019/11/18 11:37:00"},
            },
        "DisplayName": "ddek",
        "FinalBet": false,
        "IsDisabled": false,
        "IsZeroSubReturn": false,
        "JackpotThrowAmount": null,
        "JackpotThrowAmountPerPlayer": null,
        "NeighboursLength": 2,
        "PlacedAmount": 0,
        "PlacedBets": [
            {
                "Multiplier": 5000,
                "BetName": "Straight up 11"
              },
              {
                "Multiplier": 10000,
                "BetName": "Straight up 14"
              },
              {
                "Multiplier": 50,
                "BetName": "Straight up 4"
              },
              {
                "Multiplier": 10,
                "BetName": "Straight up 23"
              },
              {
                "Multiplier": 10,
                "BetName": "Straight up 22"
              },
              {
                "Multiplier": 10,
                "BetName": "Straight up 0"
              }
        ],
        "SelectedMultiplier": 5,
        "WonAmount": 0,
                    },
    "PlayerKey": "56e8f7b1-cfa2-4e63-b0f8-e0bb1ff83023",
    "ProgressPercent": "43",
    "ProgressTime": "13",
    "SpinNumber": "67879",
    "SpinsDistributionPercents": {
        "black":49,
        "Even": 52,
        "FirstHalf": 48,
                "ColdNumbers":{
                    "0": {"Number": 15, "Color": 1, "IsEven": false},
                    "1": {"Number": 32, "Color": 0, "IsEven": true},
                    "2": {"Number": 10, "Color": 1, "IsEven": true},
                    "3": {"Number": 11, "Color": 1, "IsEven": false},
                    "4": {"Number": 12, "Color": 0, "IsEven": true},
                },
                "HotNumbers":{
                    "0": {"Number": 22, "Color": 1, "IsEven": true},
                    "1": {"Number": 4, "Color": 1, "IsEven": true},
                    "2": {"Number": 36, "Color": 0, "IsEven": true},
                    "3": {"Number": 33, "Color": 1, "IsEven": false},
                    "4": {"Number": 34, "Color": 0, "IsEven": true},
                },
                "NumberStats":{
                                    "0": 5,
                                    "1": 10,
                                    "2": 10,
                                    "3": 8,
                                    "4": 10,
                                    "5": 5,
                                    "6": 5,
                                    "7": 4,
                                    "8": 9,
                                    "9": 8,
                                    "10": 3,
                                    "11": 1,
                                    "12": 3,
                                    "13": 4,
                                    "14": 5,
                                    "15": 2,
                                    "16": 5,
                                    "17": 5,
                                    "18": 5,
                                    "19": 7,
                                    "20": 2,
                                    "21": 2,
                                    "22": 10,
                                    "23": 7,
                                    "24": 6,
                                    "25": 4,
                                    "26": 5,
                                    "27": 8,
                                    "28": 5,
                                    "29": 2,
                                    "30": 4,
                                    "31": 5,
                                    "32": 4,
                                    "33": 8,
                                    "34": 2,
                                    "35": 6,
                                    "36": 6
                },
        "Nd2": 29,
        "Odd": 46,
        "Rd3": 35,
        "Red": 48,
        "SecondHalf": 52,
        "St1": 36,
        "ZeroEO": 2,
        "ZeroRB": 3
    },
    "Tournament": "{TournamentId: null, TournamentNumber: 0, GameType: null, Name: null, SpinsLeft: null, SpinIndex: 0}",
    "TournamentBetAllowed": false,
    "WinningNumber": null
}

